apiVersion: apps/v1
kind: Deployment
metadata:
  name: all
spec:
  replicas: 1
  selector:
    matchLabels:
      app: all
  template:
    metadata:
      labels:
        app: all
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: all
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "b055291c-12c1-41fa-be1e-b852de4a50cc"
        - name: Vless_Path
          value: "/vl55gf3455"
        - name: Vmess_UUID
          value: "b055291c-12c1-41fa-be1e-b852de4a50cc"
        - name: Vmess_Path
          value: "/vm66c1236"
        - name: Share_Path
          value: "/v2link"
